[package]
name = "tv"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = "0.6"
hyper = "0.14"
thiserror = "1.0"

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.21"
features = ["rt-multi-thread", "macros"]
